name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build and tag Docker image
        run: docker build -t tsmith4014/career-page:latest .

      - name: Push Docker image to Docker Hub
        run: docker push tsmith4014/career-page:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}

      - name: Deploy to Oracle instance
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.ORACLE_USERNAME }}@${{ secrets.ORACLE_HOST }} << 'EOF'
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          docker pull tsmith4014/career-page:latest
          docker stop $(docker ps -q --filter name=backend1) || true
          docker rm $(docker ps -aq --filter name=backend1) || true
          docker run -d -p 8000:8000 --name backend1 --network my_network tsmith4014/career-page:latest
          EOF
